/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app; 
//import com.entidades.Tipo;
//import com.entidades.Articulo;

import com.entidad.Articulo;
import com.entidad.Cliente;
import com.entidad.Proveedor;
import com.entidad.Tipo;
import com.informes.ArticuloR;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import util.HibernateUtil;


/**
 *
 * @author sa
 */
public class ArticuloApp extends javax.swing.JFrame {

    
    private Session st;
    private DefaultTableModel model;
   
   
   
    /**
     * Creates new form Articulo
     */
    public ArticuloApp() {
       
        initComponents();
           setLocationRelativeTo(null);
           hibernateSession();
           arranque();
       // setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_id_articulo = new javax.swing.JTextField();
        txt_descripcion_articulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_tipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_p_venta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_p_compra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_porcentaje = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        bt_nuevo = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_informe = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        jPanelPorDescripcion = new javax.swing.JPanel();
        txt_buscardorPorDescripcion = new javax.swing.JTextField();
        jLabelPorDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORMULARIO DE ARTICULOS");
        setMaximumSize(new java.awt.Dimension(587, 599));
        setMinimumSize(new java.awt.Dimension(587, 549));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/computer.png"))); // NOI18N
        jLabel1.setText("FORMULARIO DE ARTICULOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID:");

        jLabel3.setText("DESCRIPCION:");

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("TIPO ARTICULO:");

        jLabel4.setText("PRECIO VENTA:");

        txt_p_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_p_ventaActionPerformed(evt);
            }
        });
        txt_p_venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_p_ventaKeyTyped(evt);
            }
        });

        jLabel7.setText("PRECIO COMPRA:");

        txt_p_compra.setEnabled(false);
        txt_p_compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_p_compraKeyTyped(evt);
            }
        });

        jLabel8.setText("PORCENTAJE:");

        txt_porcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_porcentajeKeyTyped(evt);
            }
        });

        jLabel9.setText("CANTICAD:");

        txt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cantidadKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txt_p_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel7)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_p_compra, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(txt_cantidad)))
                                .addComponent(txt_descripcion_articulo)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_descripcion_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_p_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_p_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Descripcion Articulo", "Tipo", "Precio de Venta"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New.png"))); // NOI18N
        bt_nuevo.setText("Nuevo");
        bt_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });

        bt_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save.png"))); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit.png"))); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Trashcan_empty.png"))); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_informe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Tasks.png"))); // NOI18N
        bt_informe.setText("Informe");
        bt_informe.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_informe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_informe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_informeActionPerformed(evt);
            }
        });

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cancel32.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Search (2).png"))); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_informe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancelar)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_buscar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_nuevo)
                        .addComponent(bt_guardar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_editar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bt_eliminar)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_informe)
                            .addComponent(bt_cancelar))))
                .addContainerGap())
        );

        jPanelPorDescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_buscardorPorDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscardorPorDescripcionKeyPressed(evt);
            }
        });

        jLabelPorDescripcion.setText("POR DESCRIPCION:");

        javax.swing.GroupLayout jPanelPorDescripcionLayout = new javax.swing.GroupLayout(jPanelPorDescripcion);
        jPanelPorDescripcion.setLayout(jPanelPorDescripcionLayout);
        jPanelPorDescripcionLayout.setHorizontalGroup(
            jPanelPorDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorDescripcionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabelPorDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_buscardorPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPorDescripcionLayout.setVerticalGroup(
            jPanelPorDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPorDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscardorPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPorDescripcion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(jPanelPorDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-603)/2, (screenSize.height-617)/2, 603, 617);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_p_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_p_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_p_ventaActionPerformed

    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
        
       arranque();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        guardar();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        this.retornoArticulo();
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
       this.editar();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
       this.eliminar();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void txt_p_ventaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_p_ventaKeyTyped
    this.soloNumeros(evt);   
    
    }//GEN-LAST:event_txt_p_ventaKeyTyped

    private void txt_p_compraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_p_compraKeyTyped
       this.soloNumeros(evt);
    }//GEN-LAST:event_txt_p_compraKeyTyped

    private void txt_porcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_porcentajeKeyTyped
        this.soloNumeros(evt);
    }//GEN-LAST:event_txt_porcentajeKeyTyped

    private void txt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadKeyTyped
        this.soloNumeros(evt);
    }//GEN-LAST:event_txt_cantidadKeyTyped

    private void bt_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_informeActionPerformed
        this.informe_articulo();
         this.arranque();
    }//GEN-LAST:event_bt_informeActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
       this.bt_buscar();
        this.setSize(587,620);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void txt_buscardorPorDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscardorPorDescripcionKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER){
       // this.retornoArticulo();
          this.cargarTabla();
            try{
                 if(this.txt_buscardorPorDescripcion.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por Descripcion");
                 this.txt_buscardorPorDescripcion.requestFocus();
               }else{
                 this.limpiartabla();
             
                 this.buscadorPorDescripcionTabla();
                }
                
       }catch(Exception e){
           
       }
      }
     
     // [587, 579]
    }//GEN-LAST:event_txt_buscardorPorDescripcionKeyPressed

    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArticuloApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArticuloApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArticuloApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArticuloApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
               new ArticuloApp().setVisible(true);
               // super(parent, modal);
             
            }
        });
    }
    
   public void limpiartabla(){
      int a = model.getRowCount()-1;
         for(int i=a; i>=0; i--){
           model.removeRow(i);
      }
    }
     public void soloNumeros(KeyEvent evt){
      char car = evt.getKeyChar();
       if((car <'0' || car >'9'))
         evt.consume();
  }
    
    
    public void hibernateSession(){
        st= HibernateUtil.getSessionFactory().openSession();
    }
    
    public void arranque(){
    cargarCombo();
    this.txt_id_articulo.setEnabled(false);
    this.txt_id_articulo.setText(null);
    this.txt_descripcion_articulo.setEnabled(false);
    this.txt_descripcion_articulo.setText(null);
    this.combo_tipo.setSelectedIndex(-1);
    this.combo_tipo.setEnabled(false);
    this.txt_p_compra.setText(null);
    this.txt_p_compra.setEnabled(false);
    this.txt_p_venta.setText(null);
    this.txt_porcentaje.setEnabled(false);
    this.txt_porcentaje.setText(null);
    this.txt_cantidad.setText(null);
    this.txt_cantidad.setEnabled(false);
    this.bt_guardar.setEnabled(false);
    this.bt_guardar.setText("Guardar");
    this.bt_editar.setEnabled(false);
    this.bt_eliminar.setEnabled(false);
    this.jTable1.setEnabled(true);
    this.bt_nuevo.setEnabled(true);
    this.txt_p_venta.setEnabled(false);
    tableModel();
    cargarTabla();
    this.txt_buscardorPorDescripcion.setText(null);
    
    
     this.jPanelPorDescripcion.setVisible(false);
     this.setSize(587,579);
    
   // this.txt_buscardorPorDescripcion.setEnabled(false);
   // this.jLabelPorDescripcion.setEnabled(false);
   // this.jPanelPorDescripcion.setEnabled(false);
   // this.bt_buscar.setEnabled(true);
    
}
public void tableModel(){
    this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
    this.jTable1.getColumnModel().getColumn(0).setHeaderValue("ID");
    this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    this.jTable1.getColumnModel().getColumn(1).setHeaderValue("DESCRIPCION ARTICULO");
    this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
    this.jTable1.getColumnModel().getColumn(2).setHeaderValue("TIPO");
    this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
    this.jTable1.getColumnModel().getColumn(3).setHeaderValue("PRECIO DE VENTA");
    model = (DefaultTableModel)this.jTable1.getModel();
    model.setNumRows(0);
}


public void nuevo(){
    this.txt_descripcion_articulo.setEnabled(true);
    this.txt_descripcion_articulo.setText(null);
    this.combo_tipo.setSelectedIndex(-1);
    this.combo_tipo.setEnabled(true);
    this.txt_p_compra.setText(null);
    this.txt_p_compra.setEnabled(true);
    this.txt_p_venta.setText(null);
    this.txt_p_venta.setEnabled(true);
    this.txt_porcentaje.setEnabled(true);
    this.txt_porcentaje.setText(null);
    this.txt_cantidad.setText(null);
    this.txt_cantidad.setEnabled(true);
    this.bt_guardar.setEnabled(true); 
    this.txt_descripcion_articulo.requestFocus();
    this.txt_id_articulo.setText("Auto");
    
    this.jPanelPorDescripcion.setVisible(false);
}



public void cargarTabla(){
    
    this.limpiartabla();
    List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
    for(Articulo articuloList : lista){
        model.addRow(new Object[]{
           articuloList.getId_articulo(),
           articuloList.getDes_articulo(),
           articuloList.getTipo().getDes_tipo(),
           articuloList.getP_venta()
            
        });
    }
}

public void buscadorPorDescripcionTabla(){
      try{
        st.beginTransaction();
      String porDescripcion =this.txt_buscardorPorDescripcion.getText();
    
   //   List<Articulo> lista =(List<Articulo>)st.createQuery("FROM Articulo WHERE des_articulo LIKE '%"+porDescripcion+"%'" ).list();
      List<Articulo> lista =(List<Articulo>)st.createQuery("FROM Articulo WHERE des_articulo LIKE '%"+porDescripcion+"%'").list(); 
      for(Articulo ar : lista){
            model.addRow(new Object[]{
                ar.getId_articulo(),
                ar.getDes_articulo(),
                ar.getTipo().getDes_tipo(),
                ar.getP_venta(),
              //  ar.getCantidad(),
              //  ar.getP_compra(),
              //  ar.getPorcentaje()
            });
          
        }
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por nombre");  
     }
     this.retornoArticulo(); // carga los datos de la tabla en el formulario para modificar o eliminar.
     
    } 

 public void bt_buscar(){
         this.arranque();
         this.txt_id_articulo.setText(null);
         this.txt_cantidad.setText(null);
         this.txt_descripcion_articulo.setText(null);
         this.txt_p_compra.setText(null);
         this.txt_p_venta.setText(null);
         this.txt_porcentaje.setText(null);
       //  this.combo_tipo.removeAllItems();;
      try{
        if(this.jTable1.getRowCount()!=0  && this.jTable1.getSelectedRow()!= 0){
        st.beginTransaction();
           this.jPanelPorDescripcion.setVisible(true);
           this.txt_buscardorPorDescripcion.requestFocus();
        }else{
          JOptionPane.showMessageDialog(null,"Todavia nose a registrado ningún Descripcion.");
          this.arranque();
       }   
      }catch(Exception e){
         //JOptionPane.showMessageDialog(null,"Se puede buscar por RUC y por Nombre."); 
      }  
       
    }

public void cargarCombo(){
    this.combo_tipo.removeAllItems();
    List<Tipo> lista = (List<Tipo>)st.createQuery("From Tipo").list();
    for(Tipo tipoList : lista){
        this.combo_tipo.addItem(tipoList.getDes_tipo());            
    }
}

public void guardar(){
   if(this.txt_descripcion_articulo.getText().isEmpty()){
       JOptionPane.showMessageDialog(null,"Rellene descricion de Articulo");
        this.txt_descripcion_articulo.requestFocus();
        
   }else{
       if(this.combo_tipo.getSelectedIndex()== -1){
           JOptionPane.showMessageDialog(null,"Rellene el Tipo de Articulo");
           this.combo_tipo.requestFocus();
       }
       else{
           if(this.txt_p_venta.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Rellene el precio de venta");
                this.txt_p_venta.requestFocus();
                       
               
           }
           else{
               if(this.txt_p_compra.getText().isEmpty()){
               JOptionPane.showMessageDialog(null,"Indique el precio de Compra");
                this.txt_p_compra.requestFocus();
               
               }
               else{
                   if(this.txt_porcentaje.getText().isEmpty()){
                   JOptionPane.showMessageDialog(null,"Rellene el porcentaje de ganancia");
                    this.txt_porcentaje.requestFocus();
                   }
                   else{
                       if(this.txt_cantidad.getText().isEmpty()){
                           JOptionPane.showMessageDialog(null,"Rellene la cantidad");
                           this.txt_cantidad.requestFocus();
                       }
                       else{
                           
                        if(this.bt_guardar.getText().equals("Guardar")){
                          try{  
                            
                            
                            String desArt = this.txt_descripcion_articulo.getText();
                            Object selectedItem = this.combo_tipo.getSelectedItem();
                            Tipo retornoTipo = retornoTipo(selectedItem.toString());
                           
                             int pCompra = Integer.parseInt(this.txt_p_compra.getText());
                             int porcentaje =Integer.parseInt(this.txt_porcentaje.getText());
                             int pVenta = Integer.parseInt(this.txt_p_venta.getText());
                             int cantidad = Integer.parseInt(this.txt_cantidad.getText());
                             
                            /*         
                            int pCompra = 0;
                            try{
                                pCompra = Integer.parseInt(this.txt_p_compra.getText());
                                
                            }catch (Exception e){
                                JOptionPane.showMessageDialog(null, "Precio de compra debe ser numerico.");
                                 
                                
                                
                            }
                            int pVenta = 0;
                            try{
                                pVenta = Integer.parseInt(this.txt_p_venta.getText());
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"Precio de venta debe ser numerico.");
                            }
                            int porcentaje = 0;
                            try{
                                porcentaje =Integer.parseInt(this.txt_porcentaje.getText());
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"Porcentaje debe ser numerico.");
                            }
                            int cantidad = 0;
                            try{
                                cantidad = Integer.parseInt(this.txt_cantidad.getText());
                            }catch(Exception e){
                                JOptionPane.showMessageDialog(null,"Cantidad debe ser numerico.");
                            }
                            * 
                            * 
                            */
                             
                             
                            st.beginTransaction();
                             //   int parseInt =Integer.parseInt(this.txt_id_articulo.getText());
                               // Articulo art =(Articulo)st.load(Articulo.class, parseInt);
                                Articulo art = new Articulo();
                                art.setDes_articulo(desArt);
                                art.setTipo(retornoTipo);
                               
                                art.setP_compra(pCompra);
                                art.setP_venta(pVenta);
                                art.setPorcentaje(porcentaje);
                                art.setCantidad(cantidad);
                                
                                retornoTipo.getArticulos().add(art);
                                st.save(art);
                                st.update(retornoTipo);
                                st.getTransaction().commit();
                                JOptionPane.showMessageDialog(null, "Articulo Guardados correctamente.");
                                arranque();
                        }
                        catch(      HeadlessException | HibernateException | NumberFormatException e){
                           JOptionPane.showMessageDialog(null,"Error guardando");
                     
                       }
                      }
                                             
                     
                        else{
                                String desArt = this.txt_descripcion_articulo.getText();
                                    Object selectedItem = this.combo_tipo.getSelectedItem();
                                    Tipo retornoTipo = retornoTipo(selectedItem.toString());
                                   /*
                                    int pCompra = 0;
                                    try {
                                        pCompra = Integer.parseInt(this.txt_p_compra.getText());
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, "Precio de compra debe ser numérico.");
                                       
                                    }
                                    int pVenta = 0;
                                    try {
                                        pVenta = Integer.parseInt(this.txt_p_venta.getText());
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, "Precio de venta debe ser numérico.");
                                        
                                    }
                                    int porcentaje = 0;
                                    try {
                                        porcentaje = Integer.parseInt(this.txt_porcentaje.getText());
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, "Porcentaje debe ser numérico.");
                                    }
                                    int cantidad = 0;
                                    try {
                                        cantidad = Integer.parseInt(this.txt_cantidad.getText());
                                    } catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, "Cantidad debe ser numérico.");
                                    }
                                     
                                     
                                    */
                                    
                                     int pCompra = Integer.parseInt(this.txt_p_compra.getText());
                                     int porcentaje =Integer.parseInt(this.txt_porcentaje.getText());
                                     int pVenta = Integer.parseInt(this.txt_p_venta.getText());
                                     int cantidad = Integer.parseInt(this.txt_cantidad.getText());
                                    st.beginTransaction();
                                    int parseInt = Integer.parseInt(this.txt_id_articulo.getText());
                                    Articulo art =(Articulo) st.load(Articulo.class, parseInt);
                                    art.setDes_articulo(desArt);
                                    art.setTipo(retornoTipo);
                                    art.setP_compra(pCompra);
                                    art.setP_venta(pVenta);
                                    art.setPorcentaje(porcentaje);
                                    art.setCantidad(cantidad);
                                    retornoTipo.getArticulos().add(art);
                                    st.update(art);
                                    st.update(retornoTipo);
                                    st.getTransaction().commit();
                                    JOptionPane.showMessageDialog(null, "Artículo actualizado correctamente.");
                                    arranque();
                            }
                          }
                        }
                      }
                    }
                 }
               }
            }
  

/*
 * 
 */
  public Tipo retornoTipo(String desT){
   
      Tipo tipRet = null;
      String desTipo = desT;
      try{
          Query query =st.createQuery("From Tipo t Where t. des_tipo = ?");
          query.setParameter(0,desTipo);
         try{
             tipRet=(Tipo)query.uniqueResult();
         } 
          catch(Exception e){
           JOptionPane.showMessageDialog(null, "Hay más articulos de tipo: " + desTipo); 
      }
  }catch(HibernateException | HeadlessException e){
    
 }
      return tipRet;
 }
  
  /*
   * Cuando se seleccione una fina de la table se carga
   * en el formulario
   */
  public void retornoArticulo(){
      if(this.jTable1.isEnabled()){
          int selectedRow =this.jTable1.getSelectedRow();
          Object valueAt = model.getValueAt(selectedRow, 0);
          int idArt = Integer.parseInt(valueAt.toString());
          Articulo art = (Articulo)st.load(Articulo.class,idArt);
          this.txt_id_articulo.setText(String.valueOf(art.getId_articulo()));
          this.txt_descripcion_articulo.setText(art.getDes_articulo());
          this.combo_tipo.setSelectedItem(art.getTipo().getDes_tipo());
          this.txt_p_compra.setText(String.valueOf(art.getP_compra()));
          this.txt_p_venta.setText(String.valueOf(art.getP_venta()));
          this.txt_porcentaje.setText(String.valueOf(art.getPorcentaje()));
          this.txt_cantidad.setText(String.valueOf(art.getCantidad()));
          this.bt_editar.setEnabled(true);
          this.bt_eliminar.setEnabled(true);
          this.bt_nuevo.setEnabled(false);
      }
  }
  
  public void editar(){
      this.txt_descripcion_articulo.setEnabled(true);
      this.combo_tipo.setEnabled(true);
      this.txt_p_compra.setEnabled(true);
      this.txt_p_venta.setEnabled(true);
      this.txt_p_venta.setEnabled(true);
      this.txt_porcentaje.setEnabled(true);
      this.txt_cantidad.setEnabled(true);
      this.bt_guardar.setEnabled(true);
      this.bt_guardar.setText("Actualizar");
      this.jTable1.setEnabled(false);
      this.bt_eliminar.setEnabled(false);
      this.jPanelPorDescripcion.setVisible(false);
      this.txt_buscardorPorDescripcion.setText(null);
      this.cargarTabla();
      this.txt_descripcion_articulo.requestFocus();
  }
  public void eliminar(){
      int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Eliminacion de Registro","Desea eliminar este registro",JOptionPane.YES_NO_OPTION);
      if(showConfirmDialog == 1){
          JOptionPane.showMessageDialog(null,"Registro no Eliminado.");
      }
      else{
          st.beginTransaction();
          int selectedRow = this.jTable1.getSelectedRow();
          Object valueAt = model.getValueAt(selectedRow,0);
          int idArt = Integer.parseInt(valueAt.toString());
          Articulo art = (Articulo)st.load(Articulo.class, idArt);
          st.delete(art);
          st.getTransaction().commit();
          JOptionPane.showMessageDialog(null, "Registro Eliminado");
          arranque();
      }
  }
  
 
  
  public void informe_articulo(){
   try{
     st.beginTransaction(); 
     List articuloList = new ArrayList();
     List<Articulo> lista = (List<Articulo>)st.createQuery("From Articulo").list();
     for(Iterator<Articulo> it =lista.iterator();it.hasNext();){
         Articulo articulo = it.next();
        
         articuloList.add(new ArticuloR(articulo.getId_articulo(),
                          articulo.getDes_articulo(),
                          articulo.getTipo().getDes_tipo(),
                          articulo.getP_venta(),
                          articulo.getCantidad()));
     }
       JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("com/informes/report_articulo1.jasper")); 
        //El método siguiente nos permite pasarle los datos al reporte utilizando JRBeanCollectionDataSource y como argumento la lista que creamos más arriba.
        //La lista posee los siguiente campos: "id" "des" "tipo" "pve" "can" en coincidencia con los de nuestro archivo de reporte.
        JasperPrint fillReport = JasperFillManager.fillReport(report, null,new JRBeanCollectionDataSource(articuloList));
        //El JasperViewer para visualizar, le pasamos como argumento nuestro "fillReport" de arriba.
        JasperViewer jviewer = new JasperViewer(fillReport,false);
        //Le damos un título al reporte.
        jviewer.setTitle("Lista de Artículos.");
        //La hacemos visible.
        jviewer.setVisible(true);
   }catch(HibernateException | JRException e){
     JOptionPane.showMessageDialog(null, "Error cargando reporte.");  
       
       
}
 
 
  
      
  }
  
                 
      
       
   

 
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_informe;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JComboBox combo_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPorDescripcion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPorDescripcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_buscardorPorDescripcion;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_descripcion_articulo;
    private javax.swing.JTextField txt_id_articulo;
    private javax.swing.JTextField txt_p_compra;
    private javax.swing.JTextField txt_p_venta;
    private javax.swing.JTextField txt_porcentaje;
    // End of variables declaration//GEN-END:variables

     
 
    


    
    }

   


