/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;
import com.entidad.Cliente;
import com.entidad.Funcionario;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
//import org.hibernate.HibernateException;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import util.HibernateUtil;
/**
 *
 * @author fdbritez
 */
public class FuncionarioApp extends javax.swing.JDialog {

    /**
     * Creates new form FuncionarioApp
     */
    public FuncionarioApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.hibernateSession();
        this.arranque();
        
    }
private Session st;
private DefaultTableModel model;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_id_funcionario = new javax.swing.JTextField();
        txt_nombre_funcionario = new javax.swing.JTextField();
        txt_apellido_funcionario = new javax.swing.JTextField();
        txt_direccion_fucionario = new javax.swing.JTextField();
        txt_telefono_funcionario = new javax.swing.JTextField();
        txt_jComboBox_funcionario = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_nuevo = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_informe = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelPorNombre = new javax.swing.JLabel();
        txt_buscadorPorNombre = new javax.swing.JTextField();
        jLabelCargo = new javax.swing.JLabel();
        txt_PorCargo = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO DE FUNCIONARIOS");
        setMaximumSize(new java.awt.Dimension(690, 630));
        setMinimumSize(new java.awt.Dimension(690, 545));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("APELLIDO:");

        jLabel5.setText("DIRECCION:");

        jLabel6.setText("TELEFONO:");

        jLabel7.setText("CARGO:");

        txt_nombre_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_funcionarioActionPerformed(evt);
            }
        });

        txt_telefono_funcionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono_funcionarioKeyTyped(evt);
            }
        });

        txt_jComboBox_funcionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente General", "Gerente Surcusal", "Cajero", "Deposito", "Contabilidad", "Auxiliar" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nombre_funcionario)
                                    .addComponent(txt_apellido_funcionario)
                                    .addComponent(txt_direccion_fucionario, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_telefono_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_jComboBox_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion_fucionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txt_telefono_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_jComboBox_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(630, 320));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE Y APELLDO", "DIRECCION", "TELEFONO", "CARGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(0, 0));

        bt_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New.png"))); // NOI18N
        bt_nuevo.setText("Nuevo");
        bt_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });

        bt_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save.png"))); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit.png"))); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Trashcan_empty.png"))); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.setHideActionText(true);
        bt_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_informe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Tasks.png"))); // NOI18N
        bt_informe.setText("Informe");
        bt_informe.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_informe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_informe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_informeActionPerformed(evt);
            }
        });

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cancel32.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Search (2).png"))); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_informe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_cancelar)
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_nuevo)
                        .addComponent(bt_guardar)
                        .addComponent(bt_editar)
                        .addComponent(bt_eliminar)
                        .addComponent(bt_informe)
                        .addComponent(bt_cancelar))
                    .addComponent(bt_buscar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/user-8.png"))); // NOI18N
        jLabel1.setText("FORMULARIO DE FUNCIONARIOS");
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));

        jPanelBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPorNombre.setText("POR NOMBRE:");

        txt_buscadorPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscadorPorNombreKeyPressed(evt);
            }
        });

        jLabelCargo.setText("POR CARGO: ");

        txt_PorCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PorCargoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jLabelCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_PorCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addComponent(jLabelPorNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscadorPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorNombre)
                    .addComponent(txt_buscadorPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_PorCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBuscarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelCargo.getAccessibleContext().setAccessibleName("POR CARGO:\n");
        jLabelCargo.getAccessibleContext().setAccessibleDescription("sdasd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
       this.nuevo();
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
         this.arranque();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
       this.guardar();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
       this.obtenerFuncionaro();
    }//GEN-LAST:event_jTable5MouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
    this.editar();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
       this.eliminar();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void txt_telefono_funcionarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono_funcionarioKeyTyped
       this.soloNumeros(evt);
    }//GEN-LAST:event_txt_telefono_funcionarioKeyTyped

    private void txt_nombre_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_funcionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_funcionarioActionPerformed

    private void bt_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_informeActionPerformed
       
            this.informe_funcionario();
    
       
    }//GEN-LAST:event_bt_informeActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
         
          this.buscar();
          setSize(690,630);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void txt_buscadorPorNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorPorNombreKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         this.cargartabla();
            try{
                 if(this.txt_buscadorPorNombre.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por Nombre");
                    this.txt_buscadorPorNombre.requestFocus();
                   // this.limpiartabla();
                  //  this.cargartabla();
               }else{
                    this.limpiartabla();
                    this.buscadorPorNombreTabla();
                }    

              
       }catch(Exception e){
           
       }
      }
        
    }//GEN-LAST:event_txt_buscadorPorNombreKeyPressed

    private void txt_PorCargoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PorCargoKeyPressed
      if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         this.cargartabla();
            try{
                 if(this.txt_PorCargo.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por cargo del funcionario");
                    this.txt_PorCargo.requestFocus();
                   // this.limpiartabla();
               }else{
                    this.limpiartabla();
                    this.buscadorPorCargoTabla();
                }    

              
       }catch(Exception e){
           
       }
      }
    }//GEN-LAST:event_txt_PorCargoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FuncionarioApp dialog = new FuncionarioApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void  hibernateSession(){
        st=HibernateUtil.getSessionFactory().openSession();
        
    }
    
    public void buscadorPorNombreTabla(){
      try{
        st.beginTransaction();
      String porNombre =this.txt_buscadorPorNombre.getText();
    
      List<Funcionario> lista =(List<Funcionario>)st.createQuery("FROM Funcionario WHERE nombre_funcionario LIKE '%"+porNombre+"%'" ).list();
      
      for(Funcionario fun : lista){
            String nomApe = fun.getNombre_funcionario()+ " " + fun.getApellido_funcionario();
          
            model.addRow(new Object[]{
                fun.getId_funcionario(),
                nomApe,
                fun.getDireccion_funcionario(),
                fun.getTelefono_funcionario(),
                fun.getCargo_funcionario()
            });
        }
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por nombre");  
     }
     this.obtenerFuncionaro();
    }  
    
    
    public void buscadorPorCargoTabla(){
      try{
        st.beginTransaction();
      String porCargo =this.txt_PorCargo.getText();
    
      List<Funcionario> lista =(List<Funcionario>)st.createQuery("FROM Funcionario WHERE cargo_funcionario LIKE '%"+porCargo+"%'" ).list();
      
      for(Funcionario fun : lista){
            String nomApe = fun.getNombre_funcionario()+ " " + fun.getApellido_funcionario();
          
            model.addRow(new Object[]{
                fun.getId_funcionario(),
                nomApe,
                fun.getDireccion_funcionario(),
                fun.getTelefono_funcionario(),
                fun.getCargo_funcionario()
            });
        }
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar Cargo del Funcionario");  
     }
     this.obtenerFuncionaro();
    }  
    public void buscar(){
          this.arranque();
      
        this.txt_id_funcionario.setText(null);
        this.txt_nombre_funcionario.setText(null);
        this.txt_apellido_funcionario.setText(null);
        this.txt_direccion_fucionario.setText(null);
        this.txt_telefono_funcionario.setText(null);
        this.txt_buscadorPorNombre.setText(null);
          
          //this.txt_buscadorPorRuc.setText(null);
      try{
        if(this.jTable5.getRowCount()!=0  && this.jTable5.getSelectedRow()!= 0){
        st.beginTransaction();
           this.jPanelBuscar.setVisible(true); 
           this.txt_buscadorPorNombre.requestFocus();
        
        
        }else{
          JOptionPane.showMessageDialog(null,"Todavia nose a registrado ningún cliente.");
          this.arranque();
       }   
      }catch(Exception e){
         //JOptionPane.showMessageDialog(null,"Se puede buscar por RUC y por Nombre."); 
      }  
       
    }
    
     // metodo que limpia tabla antes de buscar los datos en la base de datos   
  public void limpiartabla(){
      int a =model.getRowCount()-1;
         for(int i=a; i>=0; i--){
           model.removeRow(i );
      }
  }
    private void arranque(){
        this.txt_id_funcionario.setText(null);
        this.txt_id_funcionario.setEnabled(false);
        this.txt_nombre_funcionario.setText(null);
        this.txt_nombre_funcionario.setEnabled(false);
        this.txt_apellido_funcionario.setText(null);
        this.txt_apellido_funcionario.setEnabled(false);
        this.txt_direccion_fucionario.setText(null);
        this.txt_direccion_fucionario.setEnabled(false);
        this.txt_telefono_funcionario.setText(null);
        this.txt_telefono_funcionario.setEnabled(false);
        this.txt_jComboBox_funcionario.setEnabled(false);
        this.txt_jComboBox_funcionario.setSelectedIndex(-1);
        // Botones
        this.bt_guardar.setEnabled(false);
        this.bt_guardar.setText("Guardar");
        this.bt_editar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_nuevo.setEnabled(true);
        this.jTable5.setEnabled(true);
        
        this.tableModel();
        this.cargartabla();
        
        this.jPanelBuscar.setVisible(false);
        this.setSize(690,545);
                 
    }
    
    
    public void tableModel(){
       
         this.jTable5.getColumnModel().getColumn(0).setPreferredWidth(25);
          this.jTable5.getColumnModel().getColumn(1).setPreferredWidth(200);
           this.jTable5.getColumnModel().getColumn(2).setPreferredWidth(140);
            this.jTable5.getColumnModel().getColumn(3).setPreferredWidth(80);
             this.jTable5.getColumnModel().getColumn(4).setPreferredWidth(100);
              
              model =(DefaultTableModel)this.jTable5.getModel();
              model.setNumRows(0);
        
    }
    
    public void cargartabla(){
        this.limpiartabla();
        st.beginTransaction();
        List<Funcionario> lista =(List<Funcionario>)st.createQuery("From Funcionario").list();
        for(Funcionario func : lista){
            String nomApe = func.getNombre_funcionario()+ " " + func.getApellido_funcionario();
            model.addRow(new Object[]{
                func.getId_funcionario(),nomApe,func.getDireccion_funcionario(),func.getTelefono_funcionario(),func.getCargo_funcionario()
            });
        }
    }
   
    public void nuevo(){
        this.txt_id_funcionario.setText("Auto");
        this.txt_nombre_funcionario.setEnabled(true);
        this.txt_nombre_funcionario.requestFocus();
        this.txt_apellido_funcionario.setEnabled(true);
        this.txt_direccion_fucionario.setEnabled(true);
        this.txt_telefono_funcionario.setEnabled(true);
        this.txt_jComboBox_funcionario.setEnabled(true);
        
        this.txt_nombre_funcionario.setText(null);
        this.txt_apellido_funcionario.setText(null);
        this.txt_direccion_fucionario.setText(null);
        this.txt_telefono_funcionario.setText(null);
        
        this.jTable5.setEnabled(false);
        this.bt_editar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        
        this.bt_guardar.setEnabled(true);
        this.bt_guardar.setText("Guardar");
        
        this.bt_nuevo.setEnabled(false);
        
    }
    
    public void guardar(){
        if(this.txt_nombre_funcionario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null ,"Falta nombre del Funcionario.");
            this.txt_nombre_funcionario.requestFocus();            
        }else{
            if(this.txt_apellido_funcionario.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Falta el apellido del Funcionario");
                this.txt_apellido_funcionario.requestFocus();
            }
            else{
                if(this.txt_direccion_fucionario.getText().isEmpty()){
                  //  JOptionPane.showMessageDialog(null ,"Falta la direccion del Funcionario");
                    JOptionPane.showMessageDialog(this, "Falta la direccion del Funcionario","Rellenar campo Direccion.",JOptionPane.QUESTION_MESSAGE);
                    this.txt_direccion_fucionario.requestFocus();
                }
                else{
                    if(this.txt_telefono_funcionario.getText().isEmpty()){
                        JOptionPane.showMessageDialog(this,"Falta el telefono del Funcionario","Rellene el campo de Telefono",JOptionPane.QUESTION_MESSAGE);
                        this.txt_telefono_funcionario.requestFocus();
                    }
                    else{
                        if(this.txt_jComboBox_funcionario.getSelectedIndex()== -1){
                            JOptionPane.showMessageDialog(this,"Falta cargo de Funcionario","Seleccione un cargo",JOptionPane.QUESTION_MESSAGE);
                            this.txt_jComboBox_funcionario.requestFocus();
                        }
                        else{
                            if(this.bt_guardar.getText().equals("Guardar")){
                                st.beginTransaction();
                                Funcionario func = new Funcionario();
                                func.setNombre_funcionario(this.txt_nombre_funcionario.getText());
                                func.setApellido_funcionario(this.txt_apellido_funcionario.getText());
                                func.setDireccion_funcionario(this.txt_direccion_fucionario.getText());
                                func.setTelefono_funcionario(this.txt_telefono_funcionario.getText());
                                func.setCargo_funcionario(String.valueOf(this.txt_jComboBox_funcionario.getSelectedItem()));
                                st.save(func);
                                st.getTransaction().commit();
                                this.arranque();
                                JOptionPane.showMessageDialog(null,"Registro guardado correctamente");
                                
                            }
                            else{
                                st.beginTransaction();
                                int selectedRow = this.jTable5.getSelectedRow();
                                int idFunc = Integer.parseInt(String.valueOf(model.getValueAt(selectedRow,0)));
                                Funcionario func = (Funcionario)st.load(Funcionario.class, idFunc);
                                func.setNombre_funcionario(this.txt_nombre_funcionario.getText());
                                func.setApellido_funcionario(this.txt_apellido_funcionario.getText());
                                func.setDireccion_funcionario(this.txt_direccion_fucionario.getText());
                                func.setTelefono_funcionario(this.txt_telefono_funcionario.getText());
                                func.setCargo_funcionario(String.valueOf(this.txt_jComboBox_funcionario.getSelectedItem()));
                                st.update(func);
                                st.getTransaction().commit();
                                this.arranque();
                                JOptionPane.showMessageDialog(null,"Registro actualizado correctamente.");
                                
                                
                            }
                        }
                    }
                }
            }
        }
        
    }
    
    public void obtenerFuncionaro(){
        if(this.jTable5.isEnabled()){
            st.beginTransaction();
            int selectedRow = this.jTable5.getSelectedRow();
            int idFunc = Integer.parseInt(String.valueOf(model.getValueAt(selectedRow, 0)));
            Funcionario func = (Funcionario)st.load(Funcionario.class,idFunc);
            this.txt_id_funcionario.setText(String.valueOf(func.getId_funcionario()));
            this.txt_nombre_funcionario.setText(func.getNombre_funcionario());
            this.txt_apellido_funcionario.setText(func.getApellido_funcionario());
            this.txt_direccion_fucionario.setText(func.getDireccion_funcionario());
            this.txt_telefono_funcionario.setText(func.getTelefono_funcionario());
            this.txt_jComboBox_funcionario.setSelectedItem(func.getCargo_funcionario());
            this.bt_editar.setEnabled(true);
            this.bt_eliminar.setEnabled(true);
                                      
        }
    }
    
    public void editar(){
       this.jPanelBuscar.setVisible(false);
       this.txt_nombre_funcionario.requestFocus();
        this.bt_nuevo.setEnabled(false);
        this.txt_nombre_funcionario.setEnabled(true);
        this.txt_apellido_funcionario.setEnabled(true);
        this.txt_direccion_fucionario.setEnabled(true);
        this.txt_telefono_funcionario.setEnabled(true);
        this.txt_jComboBox_funcionario.setEnabled(true);
        this.bt_guardar.setEnabled(true);
        this.bt_eliminar.setEnabled(false);
        this.bt_guardar.setText("Actualizar");
        this.jTable5.setEnabled(false);
      
    }
    
    public void eliminar(){
       int showConfirmDialog = JOptionPane.showConfirmDialog(null,"Eliminacion de Registro","Deseada eliminar este registro.",JOptionPane.YES_NO_OPTION);
       if(showConfirmDialog == 1){
           JOptionPane.showMessageDialog(null,"Registro no eliminado.");
       }else{
           st.beginTransaction();
           int selectedRow = this.jTable5.getSelectedRow();
           Object valueAt = model.getValueAt(selectedRow,0);
           int idArt = Integer.parseInt(valueAt.toString());
           Funcionario func = (Funcionario)st.load(Funcionario.class, idArt);
           st.delete(func);
           st.getTransaction().commit();
           JOptionPane.showMessageDialog(null, "Registro eliminado");
           this.arranque();
  }
}
public void soloNumeros(KeyEvent evt){
      char car = evt.getKeyChar();
       if((car <'0' || car >'9'))
         evt.consume();
  }



public void informe_funcionario() throws HibernateException {
        try {
            //  try {
               st.beginTransaction();
               List<Funcionario> lista = (List<Funcionario>)st.createQuery("From Funcionario").list();
             
                 
               JasperReport report = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("com/informes/report2.jasper"));
                
                
                JasperPrint fillReport =JasperFillManager.fillReport(report, null,new JRBeanCollectionDataSource(lista));
                JasperViewer jviewer = new JasperViewer(fillReport,false);
                jviewer.setTitle("Lista de funcionario");
                jviewer.setVisible(true);
                        
               
              }
             catch( HibernateException | JRException e) {    
                 JOptionPane.showMessageDialog(null,"Error cargando reporte");
                  
              }
           }
        
        /*
        } catch (JRException ex) {
            Logger.getLogger(FuncionarioApp.class.getName()).log(Level.SEVERE, null, ex);
        }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_informe;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelPorNombre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField txt_PorCargo;
    private javax.swing.JTextField txt_apellido_funcionario;
    private javax.swing.JTextField txt_buscadorPorNombre;
    private javax.swing.JTextField txt_direccion_fucionario;
    private javax.swing.JTextField txt_id_funcionario;
    private javax.swing.JComboBox txt_jComboBox_funcionario;
    private javax.swing.JTextField txt_nombre_funcionario;
    private javax.swing.JTextField txt_telefono_funcionario;
    // End of variables declaration//GEN-END:variables
}
