/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;
import com.entidad.Funcionario;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import util.HibernateUtil;
import com.entidad.Proveedor;
import com.entidad.Tipo;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.HibernateException;

/**
 *
 * @author fdbritez
 */
public class ProveedorApp extends javax.swing.JDialog {
   

    /**
     * Creates new form ProveedorApp
     */
    public ProveedorApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);//Centrar Formulario.
         hibernateSession();
         arraque();
         
        
    }
    private Session st;//Variable de clase tipo Session para manejar la sesión hibernate.
    private DefaultTableModel model; //Variable de clase tipo DefaultTableModel para trabajar con la tabla.

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id_proveedor = new javax.swing.JTextField();
        txt_descripcion_proveedor = new javax.swing.JTextField();
        txt_direccion_proveedor = new javax.swing.JTextField();
        txt_telefono_proveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bt_nuevo = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_informe = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelbuscador = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_buscadorPorNombre = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO DE PROVEEDORES");
        setMaximumSize(new java.awt.Dimension(645, 520));
        setMinimumSize(new java.awt.Dimension(645, 455));
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("DIRECCION:");

        jLabel5.setText("TELEFONO:");

        txt_id_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_proveedorActionPerformed(evt);
            }
        });

        txt_telefono_proveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono_proveedorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel4))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_descripcion_proveedor)
                    .addComponent(txt_direccion_proveedor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefono_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_descripcion_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_direccion_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefono_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(51, 51, 51))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/user-8.png"))); // NOI18N
        jLabel1.setText("FORMULARIO DE PROVEEDORES");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New.png"))); // NOI18N
        bt_nuevo.setText("Nuevo");
        bt_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_nuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });

        bt_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save.png"))); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_guardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit.png"))); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Trashcan_empty.png"))); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_eliminar.setVerifyInputWhenFocusTarget(false);
        bt_eliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_informe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Tasks.png"))); // NOI18N
        bt_informe.setText("Informe");
        bt_informe.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_informe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_informe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_informe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_informeActionPerformed(evt);
            }
        });

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cancel32.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Search (2).png"))); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(bt_informe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancelar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_buscar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_nuevo)
                        .addComponent(bt_informe)
                        .addComponent(bt_cancelar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_guardar)
                            .addComponent(bt_editar)
                            .addComponent(bt_eliminar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DESCRIPCION", "DIRECCION", "TELEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanelbuscador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("POR NOMBRE:");

        txt_buscadorPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscadorPorNombreActionPerformed(evt);
            }
        });
        txt_buscadorPorNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscadorPorNombreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelbuscadorLayout = new javax.swing.GroupLayout(jPanelbuscador);
        jPanelbuscador.setLayout(jPanelbuscadorLayout);
        jPanelbuscadorLayout.setHorizontalGroup(
            jPanelbuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscadorPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelbuscadorLayout.setVerticalGroup(
            jPanelbuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelbuscadorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelbuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_buscadorPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelbuscador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
      this.nuevo();  
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
     this.arraque();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
       this.guardar();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       this.cargarProveedor();
    }//GEN-LAST:event_jTable2MouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
       this.editar();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
      this.eliminar();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_informeActionPerformed
        this.informe();
    }//GEN-LAST:event_bt_informeActionPerformed

    private void txt_telefono_proveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono_proveedorKeyTyped
      this.soloNumeros(evt);
    }//GEN-LAST:event_txt_telefono_proveedorKeyTyped

    private void txt_id_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_proveedorActionPerformed

    private void txt_buscadorPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscadorPorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscadorPorNombreActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
       
       // this.jPanelbuscador.setVisible(true);
       
     //   this.txt_buscadorPorNombre.requestFocus();
        this.buscar();
        this.setSize(645, 520);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void txt_buscadorPorNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorPorNombreKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
         this.cargarTablaProveedor();
            try{
                 if(this.txt_buscadorPorNombre.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por Nombre");
                    this.txt_buscadorPorNombre.requestFocus();
                   
               }else{
                    this.limpiartabla();
                    this.buscadorPorNombreTabla();
                }    

              
       }catch(Exception e){
           
       }
      }
        
    }//GEN-LAST:event_txt_buscadorPorNombreKeyPressed
 public void soloNumeros(KeyEvent evt){
      char car = evt.getKeyChar();
       if((car <'0' || car >'9'))
         evt.consume();
  }
    public void hibernateSession(){
       //Abrimos una sesion como variable es de clase podremos utilizar desde
        // cualquier metodos
        st= HibernateUtil.getSessionFactory().openSession();
    }
    
    public void arraque(){
        this.txt_id_proveedor.setEnabled(false);
        this.txt_id_proveedor.setText(null);
        this.txt_direccion_proveedor.setEnabled(false);
        this.txt_direccion_proveedor.setText(null);
        this.txt_descripcion_proveedor.setEnabled(false);
        this.txt_descripcion_proveedor.setText(null);
        this.txt_telefono_proveedor.setEnabled(false);
        this.txt_telefono_proveedor.setText(null);
        this.bt_guardar.setText("Guardar");
        this.bt_nuevo.setEnabled(true);
        this.bt_guardar.setEnabled(false);
        this.bt_editar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.jTable2.setEnabled(true);
        this.defaultTableModel();
        this.cargarTablaProveedor();
       
        this.jPanelbuscador.setVisible(false);
         this.setSize(645, 455);
    }
    public void buscadorPorNombreTabla(){
      try{
        st.beginTransaction();
      String porNombre =this.txt_buscadorPorNombre.getText();
    
      List<Proveedor> lista =(List<Proveedor>)st.createQuery("FROM Proveedor WHERE des_proveedor LIKE '%"+porNombre+"%'" ).list();
      
      for(Proveedor pro : lista){
            model.addRow(new Object[]{
                pro.getId_proveedor(),
                pro.getDes_proveedor(),
                pro.getDireccion_proveedor(),
                pro.getTelefono_proveedor()
            });
        }
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por nombre");  
     }
     this.cargarProveedor();;
    }  
     public void buscar(){
          this.arraque();
      
        this.txt_id_proveedor.setText(null);
        this.txt_descripcion_proveedor.setText(null);
        this.txt_direccion_proveedor.setText(null);
        this.txt_telefono_proveedor.setText(null);
        this.txt_buscadorPorNombre.setText(null);
          
          //this.txt_buscadorPorRuc.setText(null);
      try{
        if(this.jTable2.getRowCount()!=0  && this.jTable2.getSelectedRow()!= 0){
        st.beginTransaction();
           this.jPanelbuscador.setVisible(true); 
           this.txt_buscadorPorNombre.requestFocus();
        
        
        }else{
          JOptionPane.showMessageDialog(null,"Todavia nose a registrado ningún Proveedor.");
          this.arraque();
       }   
      }catch(Exception e){
         //JOptionPane.showMessageDialog(null,"Se puede buscar por RUC y por Nombre."); 
      }  
       
    }
     public void limpiartabla(){
      int a =model.getRowCount()-1;
         for(int i=a; i>=0; i--){
           model.removeRow(i );
      }
  }
    public void cargarTablaProveedor(){
        this.limpiartabla();
        // llamamo a la variable st para iniciar la transacion con Base de datos "DB".
        st.beginTransaction();
     //obtenemos una lista de  todos los registros de la tabla proveedor de la siguiente forma.
       List<Proveedor> list= (List<Proveedor>)st.createQuery("From Proveedor").list();
      //con iterator podemos navegar por la lista anterior creada.
       for(Iterator<Proveedor> it = list.iterator(); it.hasNext(); ){
           // casteo a clase Proveedor de la lista para poder utilizar los get y set.
           Proveedor proveedor = it.next();
           // cada cliclo carga una fila nueva a la tabla con registro del DB.
           model.addRow(new Object[]{
               proveedor.getId_proveedor(),
               proveedor.getDes_proveedor(),
               proveedor.getDireccion_proveedor(),
               proveedor.getTelefono_proveedor()
           });
           
           
           
       }
    }
    
    public void editar(){
        //Activar campo para la edicion
        this.txt_descripcion_proveedor.setEnabled(true);
        this.txt_descripcion_proveedor.requestFocus();
        this.txt_direccion_proveedor.setEnabled(true);
        this.txt_telefono_proveedor.setEnabled(true);
        this.bt_nuevo.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_guardar.setEnabled(true);
        this.bt_guardar.setText("Actualizar");
        this.jTable2.setEnabled(false);
        
        this.txt_buscadorPorNombre.setText(null);
        this.jPanelbuscador.setVisible(false);
              
        
    }
    
    
    public void defaultTableModel(){
        this.jTable2.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.jTable2.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.jTable2.getColumnModel().getColumn(2).setPreferredWidth(150);
        this.jTable2.getColumnModel().getColumn(3).setPreferredWidth(70);
        //La variable model es de clase, podremos utilizar en cualquier método.
       //Nos permitira agregar, editar y eliminar datos de la tabla.
        model = (DefaultTableModel)this.jTable2.getModel();
        model.setNumRows(0);
    }
    public void nuevo(){
        this.txt_id_proveedor.setText("Auto");
        this.txt_id_proveedor.setEnabled(false);
        this.txt_descripcion_proveedor.setEnabled(true);
        this.txt_descripcion_proveedor.setText(null);
        this.txt_descripcion_proveedor.requestFocus();// ponemos el foco 
        this.txt_direccion_proveedor.setEnabled(true);
        this.txt_direccion_proveedor.setText(null);
        this.txt_telefono_proveedor.setEnabled(true);
        this.txt_telefono_proveedor.setText(null);
        this.bt_nuevo.setEnabled(false);
        this.bt_guardar.setText("Guardar");
        this.bt_guardar.setEnabled(true);
        this.jTable2.setEnabled(false);
   }
    
    public void guardar(){
        // Antes que procedamos a guardar comprobaremos que no hayan campos vacios.
        if(this.txt_descripcion_proveedor.getText().isEmpty()){
            this.txt_descripcion_proveedor.setText("-");
            guardar();
        }else{
            if(this.txt_direccion_proveedor.getText().isEmpty()){
                this.txt_direccion_proveedor.setText("-");
                guardar();
            }
            else{
                if(this.txt_telefono_proveedor.getText().isEmpty()){
                    this.txt_telefono_proveedor.setText("-");
                    guardar();
                }
                else{
                  //Tendremos dos posibles casos nuevo o actualizacion.
                  // Si el boton guardar muestra la etiqueta "Guardar se creara un nuevo requistro.  
                  if(this.bt_guardar.getText().equals("Guardar")){
                      st.beginTransaction();
                     Proveedor prov = new Proveedor();
                     prov.setDes_proveedor(this.txt_descripcion_proveedor.getText());
                     prov.setDireccion_proveedor(this.txt_direccion_proveedor.getText());
                     prov.setTelefono_proveedor(this.txt_telefono_proveedor.getText());
                     st.save(prov);
                     // el comint permite confirmar la transaccion y procesa
                     st.getTransaction().commit();
                     arraque();
                     JOptionPane.showMessageDialog(null,"Proveedor guardado correctamente");
                                           
                  }
                  else{
                   st.beginTransaction();
                   int idProv = Integer.parseInt(this.txt_id_proveedor.getText());
                   //para cargar los registro se utiliza un load con los parametros de id
                   Proveedor prov =(Proveedor)st.load(Proveedor.class, idProv);
                    prov.setDes_proveedor(this.txt_descripcion_proveedor.getText());
                    prov.setDireccion_proveedor(this.txt_direccion_proveedor.getText());
                    prov.setTelefono_proveedor(this.txt_telefono_proveedor.getText());
                    //para el caso sera un update.
                    
                    st.update(prov);
                    st.getTransaction().commit();
                    arraque();
                    JOptionPane.showMessageDialog(null, "El proveedor fue actualizado correctamente.");
                   
                  }
                }
             }
           }
         }
    
    public void cargarProveedor(){
   /* Lo siguiente permite rellenar los campos con los datos que se obtenga
    * de la fila seleccionada del jTable.
    * 
    */
        if(this.jTable2.isEnabled()){
            // se Obtiene la fila seleccionada.
          int selectedRow = this.jTable2.getSelectedRow();
          // se Obtiene el id del registro que esta en la columna "0".
          int idProv = Integer.parseInt(String.valueOf(model.getValueAt(selectedRow,0)));
          //se utiliza un load para cargar el objeto.
          Proveedor prov = (Proveedor)st.load(Proveedor.class, idProv);
          // para cargar el objeto se puede utizar los get.
          this.txt_id_proveedor.setText(String.valueOf(prov.getId_proveedor()));
          this.txt_descripcion_proveedor.setText(prov.getDes_proveedor());
          this.txt_direccion_proveedor.setText(prov.getDireccion_proveedor());
          this.txt_telefono_proveedor.setText(prov.getTelefono_proveedor());
          
          this.bt_editar.setEnabled(true);
           this.bt_eliminar.setEnabled(true);
           this.bt_nuevo.setEnabled(false);
        }
    }
    
    public void eliminar(){
        //forma de conformar una eleçiminacion de registro.
        int showConfirmDialog = JOptionPane.showConfirmDialog(null,"Eliminacion de registro","Desea elimiminar este registro.",JOptionPane.YES_NO_OPTION);
        if(showConfirmDialog == 1){
            JOptionPane.showMessageDialog(null,"Registro Elimindo.");
            
        }
        else{
            // iniciamos una transacion
            st.beginTransaction();
            //Obtenemos la fila selecionado la tabla
            int selectedRow = this.jTable2.getSelectedRow();
            // obtenemos el "id" de la columna "0" de la tabla.
            int idProv = Integer.parseInt(String.valueOf(model.getValueAt(selectedRow, 0)));
            //cargamos el objeto
            Proveedor prov = (Proveedor)st.load(Proveedor.class, idProv);
            //Eliminamos con delete
            st.delete(prov);
            // confirmamos la transacion.
            st.getTransaction().commit();
            JOptionPane.showMessageDialog(null,"Registro Eliminado");
            this.arraque();
            
            
        }
    }
    
   public void informe(){
    //try - para controlar las excepciones.
    try {
        //Creamos una lista de los datos de la table "Tipo" utilizando "List".
        st.beginTransaction();
        List<Proveedor> lista = (List<Proveedor>)st.createQuery("From Proveedor").list();
        //Utilizamos el método siguiente para cargar el reporte "TipoReport.jasper"
        //El "JRLoader.loadObject" es el cargador.
        JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("com/informes/reportProveedor.jasper")); 
        //El método siguiente nos permite pasarle los datos al reporte utilizando JRBeanCollectionDataSource y como argumento la lista que creamos más arriba.
        //La lista posee dos campos por registro: "id" y "des", los nombres se corresponden con las agregadas en el reporte diseñado.
        JasperPrint fillReport = JasperFillManager.fillReport(report, null,new JRBeanCollectionDataSource(lista));
        //El JasperViewer para visualizar, le pasamos como argumento nuestro "fillReport" de arriba.
        JasperViewer jviewer = new JasperViewer(fillReport,false);
        //Le damos un título al reporte.
        jviewer.setTitle("Lista de Proveedores.");
        //La hacemos visible.
        jviewer.setVisible(true);
    } catch (HibernateException | JRException e) {
        JOptionPane.showMessageDialog(null, "Error cargando reporte.");
    }
   }
    /**
     * @param args the command line arguments
     */
   
   public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ProveedorApp dialog = new ProveedorApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_informe;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelbuscador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_buscadorPorNombre;
    private javax.swing.JTextField txt_descripcion_proveedor;
    private javax.swing.JTextField txt_direccion_proveedor;
    private javax.swing.JTextField txt_id_proveedor;
    private javax.swing.JTextField txt_telefono_proveedor;
    // End of variables declaration//GEN-END:variables
}
