/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app;
import com.entidad.Articulo;
import com.entidad.Funcionario;
import com.entidad.Tipo;
import java.awt.event.KeyEvent;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.HibernateUtil;
import java.awt.event.KeyEvent;


/**
 *
 * @author fdbritez
 */
public final class TipoApp extends javax.swing.JDialog {

    public DefaultTableModel model;
    public Session st;
    
 

  //  private DefaultTableModel model;

    /**
     * Creates new form TipoApp
     */
    public TipoApp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sessionHibernate();
         arranque();
         setLocationRelativeTo(null);
          
    }

  
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id_tipo = new javax.swing.JTextField();
        txt_des_tipo = new javax.swing.JTextField();
        jPanelPorDescripcion = new javax.swing.JPanel();
        jLabelPorDescripcion = new javax.swing.JLabel();
        txt_buscadorPorDescripcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bt_nuevo = new javax.swing.JButton();
        bt_guardar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_informe = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORMULARIO DE TIPO DE ARTICULOS");
        setMaximumSize(new java.awt.Dimension(590, 500));
        setMinimumSize(new java.awt.Dimension(590, 415));
        setModal(true);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/package.png"))); // NOI18N
        jLabel1.setText("TIPO DE ARTICULOS");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("");
        jPanel2.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel2.setName(""); // NOI18N

        jLabel2.setText("ID:");

        jLabel3.setText("DESCRIPCION:");

        txt_id_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_id_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_des_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_des_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelPorDescripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPorDescripcion.setText("POR DESCRIPCION:");

        txt_buscadorPorDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscadorPorDescripcionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPorDescripcionLayout = new javax.swing.GroupLayout(jPanelPorDescripcion);
        jPanelPorDescripcion.setLayout(jPanelPorDescripcionLayout);
        jPanelPorDescripcionLayout.setHorizontalGroup(
            jPanelPorDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPorDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_buscadorPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPorDescripcionLayout.setVerticalGroup(
            jPanelPorDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPorDescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPorDescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPorDescripcion)
                    .addComponent(txt_buscadorPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable2.setColumnSelectionAllowed(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/New.png"))); // NOI18N
        bt_nuevo.setText("Nuevo");
        bt_nuevo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_nuevo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevoActionPerformed(evt);
            }
        });
        bt_nuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt_nuevoKeyPressed(evt);
            }
        });

        bt_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Save.png"))); // NOI18N
        bt_guardar.setText("Guardar");
        bt_guardar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_guardar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/edit.png"))); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_editar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Trashcan_empty.png"))); // NOI18N
        bt_eliminar.setText("Eliminar");
        bt_eliminar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_eliminar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_informe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Tasks.png"))); // NOI18N
        bt_informe.setText("Informe");
        bt_informe.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_informe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_informe.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_informe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_informe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_informeActionPerformed(evt);
            }
        });

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/cancel32.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_cancelar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/img/Search (2).png"))); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.setActionCommand("");
        bt_buscar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bt_buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_buscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_informe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cancelar)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_informe)
                    .addComponent(bt_buscar)
                    .addComponent(bt_nuevo)
                    .addComponent(bt_guardar)
                    .addComponent(bt_editar)
                    .addComponent(bt_eliminar)
                    .addComponent(bt_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelPorDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(507, 507, 507))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPorDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-594)/2, (screenSize.height-463)/2, 594, 463);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_tipoActionPerformed

    private void bt_nuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt_nuevoKeyPressed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_bt_nuevoKeyPressed

    private void bt_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_nuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_bt_nuevoActionPerformed

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_bt_guardarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        this.eliminar();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        this.editar();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
       this.obtenerTabla();
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        this.arranque();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_informeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_informeActionPerformed
      this.informe();
      this.arranque();
    }//GEN-LAST:event_bt_informeActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        this.obtenerTabla();
    }//GEN-LAST:event_jTable2MouseClicked

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
      // this.setSize(578, 470);
        this.bt_buscar();
        this.setSize(578, 470);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void txt_buscadorPorDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorPorDescripcionKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
       // this.retornoArticulo();
          this.cargarTabla();
            try{
                 if(this.txt_buscadorPorDescripcion.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por Descripcion");
                 this.txt_buscadorPorDescripcion.requestFocus();
               }else{
                 this.limpiartabla();
             
                 this.buscadorPorDescripcionTabla();
                }
                
       }catch(Exception e){
           
       }
      }
    }//GEN-LAST:event_txt_buscadorPorDescripcionKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TipoApp dialog = new TipoApp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
       
       
    }
     private void sessionHibernate(){
      st = HibernateUtil.getSessionFactory().openSession();
    }
     
      public void limpiartabla(){
      int a = model.getRowCount()-1;
         for(int i=a; i>=0; i--){
           model.removeRow(i);
      }
    }
     public void soloNumeros(KeyEvent evt){
      char car = evt.getKeyChar();
       if((car <'0' || car >'9'))
         evt.consume();
  }
    public void arranque(){
    this.txt_id_tipo.setEnabled(false);
    this.txt_id_tipo.setText(null);
    this.txt_des_tipo.setEnabled(false);
    this.txt_des_tipo.setText(null);
    
    this.bt_guardar.setEnabled(false);
    this.bt_editar.setEnabled(false);
    this.bt_eliminar.setEnabled(false);
    this.bt_informe.setEnabled(true);
    this.bt_nuevo.setEnabled(true);
    this.bt_guardar.setText("Guardar");
    this.jTable2.setEnabled(true);
    defaultTableModel();
    this.cargarTabla();
    this.jPanelPorDescripcion.setVisible(false);
    this.txt_buscadorPorDescripcion.setText(null);
    this.setSize(590, 420);
}
 
   public void bt_buscar(){
        this.arranque();
        this.txt_id_tipo.setEnabled(false);
        this.txt_id_tipo.setText(null);
        this.txt_des_tipo.setEnabled(false);
        this.txt_des_tipo.setText(null); 
      try{
        if(this.jTable2.getRowCount()!=0  && this.jTable2.getSelectedRow()!= 0){
        st.beginTransaction();
           this.jPanelPorDescripcion.setVisible(true);
           this.txt_buscadorPorDescripcion.requestFocus();
        }else{
          JOptionPane.showMessageDialog(null,"Todavia nose a registrado ningún Descripcion.");
          this.arranque();
       }   
      }catch(Exception e){
         //JOptionPane.showMessageDialog(null,"Se puede buscar por RUC y por Nombre."); 
      }  
       
    } 
 public void buscadorPorDescripcionTabla(){
      try{
        st.beginTransaction();
      String porDescripcion =this.txt_buscadorPorDescripcion.getText();
    
   //   List<Articulo> lista =(List<Articulo>)st.createQuery("FROM Articulo WHERE des_articulo LIKE '%"+porDescripcion+"%'" ).list();
      List<Tipo> lista =(List<Tipo>)st.createQuery("FROM Tipo WHERE des_tipo LIKE '%"+porDescripcion+"%'").list(); 
      for(Tipo tp : lista){
            model.addRow(new Object[]{
                tp.getId_tipo(),
                tp.getDes_tipo()
            });
          
        }
     }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Debes rellenar el campo buscar por nombre");  
     }
     this.obtenerTabla();
     
    } 
 
 public void cargarTabla(){
         this.limpiartabla();
        st.beginTransaction();
        List<Tipo> lista = (List<Tipo>)st.createQuery("From Tipo").list();
        for(Iterator<Tipo> it = lista.iterator();it.hasNext();){
           Tipo tipo = it.next();
           model.addRow(new Object[]{    
               tipo.getId_tipo(),tipo.getDes_tipo()
           });
        }
       st.getTransaction().commit();        
       
    }
   
    public void defaultTableModel(){
    this.jTable2.getColumnModel().getColumn(0).setPreferredWidth(20);
    this.jTable2.getColumnModel().getColumn(0).setHeaderValue("ID");
    this.jTable2.getColumnModel().getColumn(1).setPreferredWidth(350);
    this.jTable2.getColumnModel().getColumn(1).setHeaderValue("DESCRIPCION");
    model = (DefaultTableModel) this.jTable2.getModel();
    model.setNumRows(0);    
    }
     
    
    public void nuevo(){
    this.bt_nuevo.setEnabled(false);
    this.bt_guardar.setEnabled(true);
    this.txt_des_tipo.setEnabled(true);
    this.txt_id_tipo.setText("Auto");
    this.txt_des_tipo.requestFocus();
    
    this.jPanelPorDescripcion.setVisible(false);
     this.txt_buscadorPorDescripcion.setText(null);
    }
    
        public void guardar(){
        if(this.txt_des_tipo.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Imposible guardar campo vacio.");
        }
        else{
            if(this.bt_guardar.getText().equals("Guardar")){
               st.beginTransaction(); //.commit();
                Tipo t = new Tipo();
                t.setDes_tipo(this.txt_des_tipo.getText());
                st.save(t);
                st.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Registro guardado.");
                arranque();
        }
        else{
            st.beginTransaction();
            int selectedRow = this.jTable2.getSelectedRow();
            Object valueAt = model.getValueAt(selectedRow, 0);
            int idTipo = Integer.parseInt(valueAt.toString());
            Tipo t = (Tipo) st.load(Tipo.class, idTipo);
            t.setDes_tipo(this.txt_des_tipo.getText());
            st.update(t);
            st.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Registro actualizado.");
            arranque();
        }
    }
        
    }
    
   public void obtenerTabla(){
    int selectedRow = this.jTable2.getSelectedRow();//Obtenemos la fila seleccionada...
    Object valueAt = model.getValueAt(selectedRow, 0);//Obtenemos el valor de esa fila...
        int idTipo = Integer.parseInt(valueAt.toString());//Convertimos el valor en entero...
        Tipo t = (Tipo) st.load(Tipo.class, idTipo);//Hacemos un load pasando como argumento la clase Tipo y  el Id del mismo...
            this.txt_id_tipo.setText(String.valueOf(t.getId_tipo()));//Asignamos valor al JTextField id. 
            this.txt_des_tipo.setText(t.getDes_tipo());//Asignamos valor al JTextField des.
            this.txt_des_tipo.requestFocus();
            this.bt_editar.setEnabled(true);//Activamos el botón editar...
            this.bt_eliminar.setEnabled(true);//Activamos el botón eliminar...
            this.bt_nuevo.setEnabled(false);//Desactivamos el botón nuevo...
            this.bt_guardar.setText("Actualizar");//Cambiamos el de guardar...
            st.getTransaction().commit();
          //  this.txt_des_tipo.requestFocus();
  }
    
    public void editar(){
         this.jPanelPorDescripcion.setVisible(false);
         this.txt_des_tipo.requestFocus();
         this.bt_guardar.setEnabled(true);//Activamos botón gurdar...
         this.txt_des_tipo.setEnabled(true);//Activamos JTextField des...
         this.bt_eliminar.setEnabled(false);//Desactivamos botón eliminar
         this.jTable2.setEnabled(false);//Desactivamos el JTable
         this.txt_des_tipo.requestFocus();
   }
    public void eliminar(){
    int seleccion = JOptionPane.showConfirmDialog(null,"Desea eliminar el Registro.", "Eliminación de Registro.", JOptionPane.YES_NO_OPTION);//Obtnemos la selección del usuario
    if(seleccion == 1){//Comparamos la selección del usuario igual a 1 no eliminamos, si es diferente se elimina.
        JOptionPane.showMessageDialog(null, "Registro no Eliminado...");
        arranque();//Si no se elimina se llama al metodo arranque() para limpiar campos
    }
    else{//Opción eliminar seleccionada
        st.beginTransaction();//Iniciamos transacción
        int selectedRow = this.jTable2.getSelectedRow();//Obtenemos selección
        Object valueAt = model.getValueAt(selectedRow, 0);//Recuperamos valor
        int idTipo = Integer.parseInt(valueAt.toString());//Convertimos valor en entero
        Tipo t = (Tipo) st.load(Tipo.class, idTipo);//Hacemos un load pasando como argumento la clase Tipo y  el Id del mismo...
        st.delete(t);//Utilizamos delete pasando como argumento el objeto Tipo que cargamos con load...
        st.getTransaction().commit();//Confirmamos la transacción...
        JOptionPane.showMessageDialog(null, "Registro Eliminado...");//Indicamos al usuario que el proceso fue exitoso...
        arranque();//Limpiamos campos con el metodo arranque()...
    }
}

 public void informe(){
    //try - para controlar las excepciones.
    try {
        //Creamos una lista de los datos de la table "Tipo" utilizando "List".
        st.beginTransaction();
        List<Tipo> lista = (List<Tipo>)st.createQuery("From Tipo").list();
        //Utilizamos el método siguiente para cargar el reporte "TipoReport.jasper"
        //El "JRLoader.loadObject" es el cargador.
        JasperReport report  = (JasperReport)JRLoader.loadObject(ClassLoader.getSystemResource("com/informes/report1.jasper")); 
        //El método siguiente nos permite pasarle los datos al reporte utilizando JRBeanCollectionDataSource y como argumento la lista que creamos más arriba.
        //La lista posee dos campos por registro: "id" y "des", los nombres se corresponden con las agregadas en el reporte diseñado.
        JasperPrint fillReport = JasperFillManager.fillReport(report, null,new JRBeanCollectionDataSource(lista));
        //El JasperViewer para visualizar, le pasamos como argumento nuestro "fillReport" de arriba.
        JasperViewer jviewer = new JasperViewer(fillReport,false);
        //Le damos un título al reporte.
        jviewer.setTitle("Lista de Tipos de Artículos.");
        //La hacemos visible.
        jviewer.setVisible(true);
    } catch (HibernateException | JRException e) {
        JOptionPane.showMessageDialog(null, "Error cargando reporte.");
    }
}    
 
    
   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_informe;
    private javax.swing.JButton bt_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelPorDescripcion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPorDescripcion;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_buscadorPorDescripcion;
    private javax.swing.JTextField txt_des_tipo;
    private javax.swing.JTextField txt_id_tipo;
    // End of variables declaration//GEN-END:variables

}   

